version: '3'

services:
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: iamin
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    networks:
      - net

networks:
  net:
